//
//  CoachFeedbackModel.swift
//  WorkoutChallenge
//
//  SwiftData persistence for the calibrated-coach output. One row per
//  generated feedback — usually one per workout, but a user may regenerate
//  with a different narrator/voice and we'll keep the most recent.
//
//  What lives here vs. on disk:
//
//    • Text fields (body, factsJSON, provenance metadata) live on this row
//      so they ride CloudKit sync to the user's other devices and show up
//      offline.
//    • Audio (mp3 from ElevenLabs / system TTS) does NOT live here — it
//      lives in `Caches/CoachAudio/{id}.mp3`. Audio files are 50-200KB and
//      would bloat CloudKit sync; iOS can also evict the Caches directory
//      under storage pressure, which is fine — `audioGeneratedAt` lets us
//      detect a missing file and regenerate on next play.
//
//  CloudKit-safe: every field has a default value. No unique constraints
//  on `workoutID` (multiple feedback rows per workout are tolerated; the
//  loader picks the most recent).
//

import Foundation
import SwiftData

@Model
final class CoachFeedbackModel {

    // MARK: - Identity

    var id: UUID = UUID()

    /// The workout this feedback is about. Not a SwiftData relationship —
    /// kept as a UUID so the row survives cleanly if the workout is later
    /// deleted (audit trail / "what did the coach say last time?").
    var workoutID: UUID = UUID()

    /// When the text portion was produced. The `audioGeneratedAt` field
    /// below tracks the audio separately because text and audio are
    /// generated by different services and may diverge.
    var generatedAt: Date = Date()

    // MARK: - Provenance

    /// Which narrator produced `body`. Stored as a string so adding
    /// providers doesn't require a schema migration.
    /// Values: "deterministic" | "foundationModel" | "anthropic" | "gemini"
    var narratorProviderRaw: String = NarratorProvider.deterministic.rawValue

    /// Which voice tier produced the audio file (if any). Nil when there
    /// is no audio — the card just renders text.
    /// Values: "elevenLabs" | "system" | nil
    var voiceProviderRaw: String?

    /// Which voice ID was used (ElevenLabs voice_id, or system voice
    /// identifier). Nil when no audio.
    var voiceID: String?

    /// When the audio file was produced. Used by the player to detect
    /// "audio was meant to exist but the file is gone (Caches eviction) —
    /// regenerate on next play." Nil when no audio was ever produced.
    var audioGeneratedAt: Date?

    // MARK: - Content

    /// The narrative text. For `.deterministic` rows this is empty —
    /// callers render the facts directly. For LLM-narrated rows, this is
    /// the 2-4 sentence response the model generated.
    var body: String = ""

    /// The facts the narrator was given (JSON-encoded `[CoachFact]`).
    /// Persisted so the card can re-render bullets even when LLM output
    /// is unavailable, AND so future debugging can answer "what did the
    /// model see when it said that?"
    var factsJSON: Data = Data()

    // MARK: - Init

    init(
        id: UUID = UUID(),
        workoutID: UUID,
        generatedAt: Date = Date(),
        narratorProvider: NarratorProvider = .deterministic,
        voiceProvider: VoiceProvider? = nil,
        voiceID: String? = nil,
        audioGeneratedAt: Date? = nil,
        body: String = "",
        factsJSON: Data = Data()
    ) {
        self.id = id
        self.workoutID = workoutID
        self.generatedAt = generatedAt
        self.narratorProviderRaw = narratorProvider.rawValue
        self.voiceProviderRaw = voiceProvider?.rawValue
        self.voiceID = voiceID
        self.audioGeneratedAt = audioGeneratedAt
        self.body = body
        self.factsJSON = factsJSON
    }

    // MARK: - Typed accessors

    var narratorProvider: NarratorProvider {
        get { NarratorProvider(rawValue: narratorProviderRaw) ?? .deterministic }
        set { narratorProviderRaw = newValue.rawValue }
    }

    var voiceProvider: VoiceProvider? {
        get { voiceProviderRaw.flatMap(VoiceProvider.init(rawValue:)) }
        set { voiceProviderRaw = newValue?.rawValue }
    }

    /// Decoded facts. Returns `.empty` if the JSON is missing or malformed.
    /// Callers that want to render bullets in the card should read this.
    var facts: CoachFacts {
        guard !factsJSON.isEmpty,
              let decoded = try? JSONDecoder().decode([CoachFact].self, from: factsJSON)
        else { return .empty }
        return CoachFacts(all: decoded)
    }
}

// MARK: - Provenance enums

enum NarratorProvider: String, Codable, Sendable, CaseIterable {
    /// Layer 1 only — facts rendered as bullets, no LLM.
    case deterministic
    /// Apple's on-device Foundation Models framework (iOS 26+).
    case foundationModel
    /// Anthropic API — claude-sonnet-4-6 (or opus when configured).
    case anthropic
    /// Google API — gemini-2.5-flash or gemini-2.5-pro.
    case gemini
}

enum VoiceProvider: String, Codable, Sendable, CaseIterable {
    /// ElevenLabs TTS — typically the user's cloned voice.
    case elevenLabs
    /// `AVSpeechSynthesizer` — free, offline fallback.
    case system
}

// CoachFact's `Codable` conformance is declared directly on the type in
// `CoachFacts.swift` — Swift only auto-synthesizes Codable when the
// conformance is declared in the same file as the type. The `facts`
// computed accessor below relies on it.
